### PR TITLE
Add table output

### PR DESCRIPTION
**Pull request by KeisukeYamashita**
## What

* Add table output format. You can specify by `-o table`

```
$ go run main.go test -p examples/kubernetes/policy examples/kubernetes/service.yaml -o table
+---------+----------------------------------+--------------------------------+
| RESULT  |               FILE               |            MESSAGE             |
+---------+----------------------------------+--------------------------------+
| success | examples/kubernetes/service.yaml |                                |
| warning | examples/kubernetes/service.yaml | Found service hello-kubernetes |
|         |                                  | but services are not allowed   |
+---------+----------------------------------+--------------------------------+
```

## Why

* To address #86

### CODE REVIEW

**Comment by KeisukeYamashita** [comment]
Test was missing. I will add them.

**Comment by KeisukeYamashita** [comment]
Added tests.

**Comment by boranx** [comment]
@KeisukeYamashita  can you resolve the conflicts? 
I'll merge it.

**Comment by KeisukeYamashita** [comment]
@boranx I resolved the conflicts. Thank you for your review.

**Pull request merged**
