### PR TITLE
feat: Recursively search directories for Rego files when compiling po…

### PR DESCRIPTION
**Pull request by Blokje5**
fixes: #79

Use `filepath.Walk` to recursively search all Rego files at the given path. Also handles the situation where a single policy file is specified with the `--policy` flag.

### CODE REVIEW

**Comment by jpreese** [comment]
Thanks for putting this together, @Blokje5!

At first glance, this seems good to me. Could you add some test cases to prove out the functionality?

**Comment by jpreese** [comment]
Thanks for adding those! Though the test looks to be adding real files.

My thought was that now that we're starting to break into the realm of needing to traverse directories, and do a bit more than just read in a file, that we might want to invest some time into an inmemory filesystem for testing purposes.

If this isn't something you're particularity comfortable with, or don't want to spend time on, then I'd like to just merge in your original PR because there's value in what you've done! And I don't want to be a roadblock. We can always add the test after the fact.

Thoughts? 

_Pinging @garethr as well_

**Comment by jpreese** [comment]
That could be an option, yep. Depending on how much functionality we actually expect to use when it comes to interacting with the filesystem, it may be better to just wrap the `os` calls ourselves.

But I'm OK with punting that down the road so we can get this functionality in here. If you want to revert that test case out so we're not writing to disk on `go test`, I think we should be good to merge unless Gareth has any other thoughts.

**Comment by garethr** [comment]
Looks good, good improvement.

**Comment by kmcquade** [comment]
@garethr can we get a new release please? I can compile it on my own but I'd like to have other members of my team do it with a real release with this feature.

**Pull request merged**
